steps:
  # 1. Build da imagem Docker unificada
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/selfservice-repo/selfservice-app', '.']

  # 2. Push da imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/selfservice-repo/selfservice-app']

  # 3. Deploy no Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'self-service-platform'
      - '--image'
      - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/selfservice-repo/selfservice-app'
      - '--region'
      - 'southamerica-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://postgres.tgkecxmbsqqjcucfizkd:zwvyF79naObFyact@aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true'

images:
  - 'southamerica-east1-docker.pkg.dev/$PROJECT_ID/selfservice-repo/selfservice-app'
